"""criando_tabela_fhir_patients

Revision ID: 0f7a52fb5985
Revises: 95c949257347
Create Date: 2026-09-02 15:01:58.186318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f7a52fb5985'
down_revision: Union[str, Sequence[str], None] = '95c949257347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fhir_patients',
    sa.Column('fhir_id', sa.String(), nullable=False),
    sa.Column('resource', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fhir_patients_fhir_id'), 'fhir_patients', ['fhir_id'], unique=True)
    op.create_index(op.f('ix_fhir_patients_id'), 'fhir_patients', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fhir_patients_id'), table_name='fhir_patients')
    op.drop_index(op.f('ix_fhir_patients_fhir_id'), table_name='fhir_patients')
    op.drop_table('fhir_patients')
    # ### end Alembic commands ###
